version: '3.8'

services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: ${CONTAINER_NAME}-mysql
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql/data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${CONTAINER_NAME}-phpmyadmin
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: ${CONTAINER_NAME}-mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: ${PMA_UPLOAD_LIMIT}
    depends_on:
      - mysql
    restart: always